### ISSUE TITLE
要用什么语言写呀？

### ISSUE THREAD

**Issue by zenozeng** [Senorsen/git-auto-pull#1]
@Senorsen

**Comment by Senorsen** [comment]
噗，已经写好并上线在求是潮各大服务器一个星期左右了……稳定运行……

是用C写的。

目前代码比较丑陋（可能有一点漏洞），所以还在清理代码阶段，计划清理差不多了后就放在这儿开源。

**Comment by Senorsen** [comment]
https://git.zjuqsc.com/apps/git-auto-pull

**Comment by zenozeng** [comment]
好的嘛，居然是Ｃ。

**Comment by Senorsen** [comment]
@zenozeng 嗯嗯，因为当初考虑了树莓派之类的小家伙，大约能节省一点资源之类……

**Comment by zenozeng** [comment]
不如用 go

**Comment by richard1122** [comment]
hhh

**Comment by Senorsen** [comment]
#5
